spring:
    application:
        name: platzy-pizzeria
    datasource:
        driver-class-name: org.h2.Driver
        username: a
        password: a
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update